Add Choose Editor

diff --git a/funclib b/funclib
--- a/funclib
+++ b/funclib
@@ -21,12 +21,22 @@
 #-------------------------------------------------------------------------------
 # Run this script after your first boot with archlinux (as root)
 
+#-------------------------------------------------------------------------------
+##### GLOBAL SETTINGS
 #GLOBAL VARIABLES {{{
   checklist=( 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 )
   UEFI=0 # BOOTLOADER CHECK
   XPINGS=0 # CONNECTION CHECK
   TRIM=0 # TRIM CHECK
   AUTOMATIC_MODE=0 # Not needed for the moment
+  AUI_DIR=`pwd` #CURRENT DIRECTORY
+  [[ $1 == -v || $1 == --verbose ]] && VERBOSE_MODE=1 || VERBOSE_MODE=0 # VERBOSE MODE
+  LOG="${AUI_DIR}/`basename ${0}`.log" # LOG FILE
+  [[ -f $LOG ]] && rm -f $LOG
+  PKG=""
+  PKG_FAIL="${AUI_DIR}/`basename ${0}`_fail_install.log"
+  [[ -f $PKG_FAIL ]] && rm -f $PKG_FAIL
+  SPIN="/-\|" #SPINNER POSITION
   # COLORS {{{
     Bold=$(tput bold)
     Underline=$(tput sgr 0 1)
@@ -53,9 +63,52 @@
     prompt2="Enter n° of options (ex: 1 2 3 or 1-3): "
     prompt3="You have to manually enter the following commands, then press ${BYellow}ctrl+d${Reset} or type ${BYellow}exit${Reset}:"
   #}}}
+  #COMMON FUNCTIONS {{{
+  error_msg() { #{{{
+    local _msg="${1}"
+    echo -e "${_msg}"
+    exit 1
+  } #}}}
+  cecho() { #{{{
+    echo -e "$1"
+    echo -e "$1" >>"$LOG"
+    tput sgr0;
+  } #}}}
+  ncecho() { #{{{
+    echo -ne "$1"
+    echo -ne "$1" >>"$LOG"
+    tput sgr0
+  } #}}}
+  spinny() { #{{{
+    echo -ne "\b${SPIN:i++%${#SPIN}:1}"
+  } #}}}
+  progress() { #{{{
+    ncecho "  ";
+    while true; do
+      kill -0 $pid &> /dev/null;
+      if [[ $? == 0 ]]; then
+        spinny
+        sleep 0.25
+      else
+        ncecho "\b\b";
+        wait $pid
+        retcode=$?
+        echo -ne "$pid's retcode: $retcode" >> $LOG
+        if [[ $retcode == 0 ]] || [[ $retcode == 255 ]]; then
+          cecho success
+        else
+          cecho failed
+          echo -e "$PKG" >> $PKG_FAIL
+          tail -n 15 $LOG
+        fi
+        break
+      fi
+    done
+  } #}}}
 #}}}
 
-
+#-------------------------------------------------------------------------------
+##### Basic Functionalities
 #COMMON FUNCTIONS {{{
   pause_function() { #{{{
     print_line
@@ -193,18 +246,18 @@
   } #}}}
   check_trim() { #{{{
     [[ -n $(hdparm -I /dev/sda | grep TRIM &> /dev/null) ]] && TRIM=1
-  }
+  } #}}}
+
+  #-------------------------------------------------------------------------------
+  ##### String Manipulation
+  contains_element() { #{{{
+      #check if an element exist in a string
+      for e in "${@:2}"; do [[ $e == $1 ]] && break; done;
+    } #}}}
 #}}}
 
 #-------------------------------------------------------------------------------
-##### String Manipulation
-contains_element() { #{{{
-    #check if an element exist in a string
-    for e in "${@:2}"; do [[ $e == $1 ]] && break; done;
-  } #}}}
-
-#-------------------------------------------------------------------------------
-##### Install Functionalities
+##### Setings Functionalities
 #ARCHLINUX INSTALL SCRIPTS MODE {{{
   #SELECT KEYMAP {{{
   select_keymap(){
@@ -222,4 +275,82 @@ contains_element() { #{{{
       fi
       done
   } #}}}
+  #DEFAULT EDITOR {{{
+  select_clieditor(){
+    print_title "DEFAULT EDITOR"
+    editors_list=("nano" "vi" "vim" "neovim");
+    PS3="$prompt1"
+    echo -e "Select editor:\n"
+    select EDITOR in "${editors_list[@]}"; do
+      if contains_element "$EDITOR" "${editors_list[@]}"; then
+        package_install "$EDITOR"
+        break
+      else
+        invalid_option
+      fi
+    done
+  }
   #}}}
+#}}}
+
+#-------------------------------------------------------------------------------
+##### Software Functionalities
+#ARCHLINUX PACKAGE MANAGEMENT {{{
+  is_package_installed() { #{{{
+    #check if a package is already installed
+    for PKG in $1; do
+      pacman -Q $PKG &> /dev/null && return 0;
+    done
+    return 1
+  } #}}}
+  package_install() { #{{{
+    print_info "Installing Package"
+    pause_function
+    #install packages using pacman
+    if [[ $AUTOMATIC_MODE -eq 1 || $VERBOSE_MODE -eq 0 ]]; then
+      for PKG in ${1}; do
+        local _pkg_repo=`pacman -Sp --print-format %r ${PKG} | uniq | sed '1!d'`
+        case $_pkg_repo in
+          "core")
+            _pkg_repo="${BRed}${_pkg_repo}${Reset}"
+            ;;
+          "extra")
+            _pkg_repo="${BYellow}${_pkg_repo}${Reset}"
+            ;;
+          "community")
+            _pkg_repo="${BGreen}${_pkg_repo}${Reset}"
+            ;;
+          "multilib")
+            _pkg_repo="${BCyan}${_pkg_repo}${Reset}"
+            ;;
+        esac
+        if ! is_package_installed "${PKG}" ; then
+          ncecho " ${BBlue}[${Reset}${Bold}X${BBlue}]${Reset} Installing (${_pkg_repo}) ${Bold}${PKG}${Reset} "
+          pacman -S --noconfirm --needed ${PKG} >>"$LOG" 2>&1 &
+          pid=$!;progress $pid
+        else
+          cecho " ${BBlue}[${Reset}${Bold}X${BBlue}]${Reset} Installing (${_pkg_repo}) ${Bold}${PKG}${Reset} exists "
+        fi
+      done
+    else
+      pacman -S --needed ${1}
+    fi
+  } #}}}
+  package_remove() { #{{{
+    #remove package
+    for PKG in ${1}; do
+      if is_package_installed "${PKG}" ; then
+        if [[ $AUTOMATIC_MODE -eq 1 || $VERBOSE_MODE -eq 0 ]]; then
+          ncecho " ${BBlue}[${Reset}${Bold}X${BBlue}]${Reset} Removing ${Bold}${PKG}${Reset} "
+          pacman -Rcsn --noconfirm ${PKG} >>"$LOG" 2>&1 &
+          pid=$!;progress $pid
+        else
+         pacman -Rcsn ${PKG}
+        fi
+      fi
+    done
+  } #}}}
+  system_update() { #{{{
+    pacman -Sy
+  } #}}}
+#}}}
